#!/bin/bash

MYSQL01=$( docker run -d paulczar/mysql mysqld_safe --server-id=1 --log-bin=mysql-bin --log-slave-updates=1 --auto_increment_increment=2 --auto_increment_offset=1 )
MYSQL01_IP=$(docker inspect $MYSQL01 | grep IPAd | awk -F'"' '{print $4}')

MYSQL02=$(docker run -d paulczar/mysql mysqld_safe --server-id=2 --log-bin=mysql-bin --log-slave-updates=1 --auto_increment_increment=2 --auto_increment_offset=2)
MYSQL02_IP=$(docker inspect $MYSQL02 | grep IPAd | awk -F'"' '{print $4}')

docker ps

echo "wait 2 seconds for mysql to start"
sleep 2

echo "Creating replication user..."
mysql -uroot -proot -h $MYSQL01_IP -AN -e 'GRANT REPLICATION SLAVE ON *.* TO "replication"@"%" IDENTIFIED BY "password";'
mysql -uroot -proot -h $MYSQL01_IP -AN -e 'flush privileges;'

echo "Exporting Data from MySQL01 to MySQL02..."
mysqldump -uroot -proot -h $MYSQL01_IP --single-transaction --all-databases \
	--flush-privileges | mysql -uroot -proot -h $MYSQL02_IP

echo "Set MySQL01 as master on MySQL02..."
MYSQL01_Position=$(mysql -uroot -proot -h $MYSQL01_IP -e "show master status \G" | grep Position | awk '{print $2}')
MYSQL01_File=$(mysql -uroot -proot -h $MYSQL01_IP -e "show master status \G"     | grep File     | awk '{print $2}')

mysql -uroot -proot -h $MYSQL02_IP -AN -e "CHANGE MASTER TO master_host='$MYSQL01_IP', master_port=3306, \
	master_user='replication', master_password='password', master_log_file='$MYSQL01_File', \
	master_log_pos=$MYSQL01_Position;"


echo "Set MySQL02 as master on MySQL01..."
MYSQL02_Position=$(mysql -uroot -proot -h $MYSQL02_IP -e "show master status \G" | grep Position | awk '{print $2}')
MYSQL02_File=$(mysql -uroot -proot -h $MYSQL02_IP -e "show master status \G"     | grep File     | awk '{print $2}')

mysql -uroot -proot -h $MYSQL01_IP -AN -e "CHANGE MASTER TO master_host='$MYSQL02_IP', master_port=3306, \
	master_user='replication', master_password='password', master_log_file='$MYSQL02_File', \
	master_log_pos=$MYSQL02_Position;"

echo "Start Slave on both Servers..."
mysql -uroot -proot -h $MYSQL01_IP -AN -e "start slave;"
mysql -uroot -proot -h $MYSQL02_IP -AN -e "start slave;"

echo "Create database 'wordpress' on MySQL01..."

mysql -uroot -proot -h $MYSQL01_IP -e "create database wordpress;"

echo "Wait 2 seconds, then check that it exists on MySQL02..."

sleep 2
mysql -uroot -proot -h $MYSQL02_IP -e "show databases;"

echo "Okay,  now lets stick a HAProxy in front of them..."

mysql -uroot -proot -h $MYSQL01_IP -AN -e "GRANT USAGE ON *.* TO 'haproxy'@'%';"

HAPROXY_MYSQL=$(docker run -d paulczar/haproxy-mysql /haproxy/start "server Primary $MYSQL01_IP:3306" "server Secondary $MYSQL02_IP:3306")
HAPROXY_MYSQL_IP=$(docker inspect $HAPROXY_MYSQL | grep IPAd | awk -F'"' '{print $4}')

echo HAPROXY IS $HAPROXY_MYSQL_IP

echo "Check our haproxy works..."
echo "should show alternating server_id"

mysql -uroot -proot -h $HAPROXY_MYSQL_IP -e 'show variables like "server_id" \G'
mysql -uroot -proot -h $HAPROXY_MYSQL_IP -e 'show variables like "server_id" \G'
mysql -uroot -proot -h $HAPROXY_MYSQL_IP -e 'show variables like "server_id" \G'
mysql -uroot -proot -h $HAPROXY_MYSQL_IP -e 'show variables like "server_id" \G'

echo "Cool.   Now a wordpress ..."


WORDPRESS1=$(docker run -d paulczar/apache2-wordpress /var/www/start $HAPROXY_MYSQL_IP)
WORDPRESS1_IP=$(docker inspect $WORDPRESS1 | grep IPAd | awk -F'"' '{print $4}')

echo "Browse to http://$WORDPRESS1_IP to access your wordpress site"
